// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MainService.proto

package com.nguyenduc.grpc;

public final class MainServiceOuterClass {
  private MainServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ServiceGrpcRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.nguyenduc.grpc.ServiceGrpcRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string requestId = 1;</code>
     */
    java.lang.String getRequestId();
    /**
     * <code>string requestId = 1;</code>
     */
    com.google.protobuf.ByteString
        getRequestIdBytes();

    /**
     * <code>string functionName = 2;</code>
     */
    java.lang.String getFunctionName();
    /**
     * <code>string functionName = 2;</code>
     */
    com.google.protobuf.ByteString
        getFunctionNameBytes();

    /**
     * <code>string jsonData = 3;</code>
     */
    java.lang.String getJsonData();
    /**
     * <code>string jsonData = 3;</code>
     */
    com.google.protobuf.ByteString
        getJsonDataBytes();

    /**
     * <code>string lmid = 8;</code>
     */
    java.lang.String getLmid();
    /**
     * <code>string lmid = 8;</code>
     */
    com.google.protobuf.ByteString
        getLmidBytes();
  }
  /**
   * Protobuf type {@code com.nguyenduc.grpc.ServiceGrpcRequest}
   */
  public  static final class ServiceGrpcRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.nguyenduc.grpc.ServiceGrpcRequest)
      ServiceGrpcRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ServiceGrpcRequest.newBuilder() to construct.
    private ServiceGrpcRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ServiceGrpcRequest() {
      requestId_ = "";
      functionName_ = "";
      jsonData_ = "";
      lmid_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ServiceGrpcRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              requestId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              functionName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              jsonData_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              lmid_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nguyenduc.grpc.MainServiceOuterClass.internal_static_com_nguyenduc_grpc_ServiceGrpcRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nguyenduc.grpc.MainServiceOuterClass.internal_static_com_nguyenduc_grpc_ServiceGrpcRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcRequest.class, com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcRequest.Builder.class);
    }

    public static final int REQUESTID_FIELD_NUMBER = 1;
    private volatile java.lang.Object requestId_;
    /**
     * <code>string requestId = 1;</code>
     */
    public java.lang.String getRequestId() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestId_ = s;
        return s;
      }
    }
    /**
     * <code>string requestId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FUNCTIONNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object functionName_;
    /**
     * <code>string functionName = 2;</code>
     */
    public java.lang.String getFunctionName() {
      java.lang.Object ref = functionName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        functionName_ = s;
        return s;
      }
    }
    /**
     * <code>string functionName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFunctionNameBytes() {
      java.lang.Object ref = functionName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        functionName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int JSONDATA_FIELD_NUMBER = 3;
    private volatile java.lang.Object jsonData_;
    /**
     * <code>string jsonData = 3;</code>
     */
    public java.lang.String getJsonData() {
      java.lang.Object ref = jsonData_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jsonData_ = s;
        return s;
      }
    }
    /**
     * <code>string jsonData = 3;</code>
     */
    public com.google.protobuf.ByteString
        getJsonDataBytes() {
      java.lang.Object ref = jsonData_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jsonData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LMID_FIELD_NUMBER = 8;
    private volatile java.lang.Object lmid_;
    /**
     * <code>string lmid = 8;</code>
     */
    public java.lang.String getLmid() {
      java.lang.Object ref = lmid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lmid_ = s;
        return s;
      }
    }
    /**
     * <code>string lmid = 8;</code>
     */
    public com.google.protobuf.ByteString
        getLmidBytes() {
      java.lang.Object ref = lmid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lmid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRequestIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestId_);
      }
      if (!getFunctionNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, functionName_);
      }
      if (!getJsonDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, jsonData_);
      }
      if (!getLmidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, lmid_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRequestIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requestId_);
      }
      if (!getFunctionNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, functionName_);
      }
      if (!getJsonDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, jsonData_);
      }
      if (!getLmidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, lmid_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcRequest)) {
        return super.equals(obj);
      }
      com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcRequest other = (com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcRequest) obj;

      boolean result = true;
      result = result && getRequestId()
          .equals(other.getRequestId());
      result = result && getFunctionName()
          .equals(other.getFunctionName());
      result = result && getJsonData()
          .equals(other.getJsonData());
      result = result && getLmid()
          .equals(other.getLmid());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
      hash = (53 * hash) + getRequestId().hashCode();
      hash = (37 * hash) + FUNCTIONNAME_FIELD_NUMBER;
      hash = (53 * hash) + getFunctionName().hashCode();
      hash = (37 * hash) + JSONDATA_FIELD_NUMBER;
      hash = (53 * hash) + getJsonData().hashCode();
      hash = (37 * hash) + LMID_FIELD_NUMBER;
      hash = (53 * hash) + getLmid().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.nguyenduc.grpc.ServiceGrpcRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.nguyenduc.grpc.ServiceGrpcRequest)
        com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nguyenduc.grpc.MainServiceOuterClass.internal_static_com_nguyenduc_grpc_ServiceGrpcRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nguyenduc.grpc.MainServiceOuterClass.internal_static_com_nguyenduc_grpc_ServiceGrpcRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcRequest.class, com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcRequest.Builder.class);
      }

      // Construct using com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        requestId_ = "";

        functionName_ = "";

        jsonData_ = "";

        lmid_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nguyenduc.grpc.MainServiceOuterClass.internal_static_com_nguyenduc_grpc_ServiceGrpcRequest_descriptor;
      }

      @java.lang.Override
      public com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcRequest getDefaultInstanceForType() {
        return com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcRequest build() {
        com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcRequest buildPartial() {
        com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcRequest result = new com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcRequest(this);
        result.requestId_ = requestId_;
        result.functionName_ = functionName_;
        result.jsonData_ = jsonData_;
        result.lmid_ = lmid_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcRequest) {
          return mergeFrom((com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcRequest other) {
        if (other == com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcRequest.getDefaultInstance()) return this;
        if (!other.getRequestId().isEmpty()) {
          requestId_ = other.requestId_;
          onChanged();
        }
        if (!other.getFunctionName().isEmpty()) {
          functionName_ = other.functionName_;
          onChanged();
        }
        if (!other.getJsonData().isEmpty()) {
          jsonData_ = other.jsonData_;
          onChanged();
        }
        if (!other.getLmid().isEmpty()) {
          lmid_ = other.lmid_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object requestId_ = "";
      /**
       * <code>string requestId = 1;</code>
       */
      public java.lang.String getRequestId() {
        java.lang.Object ref = requestId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string requestId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRequestIdBytes() {
        java.lang.Object ref = requestId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string requestId = 1;</code>
       */
      public Builder setRequestId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string requestId = 1;</code>
       */
      public Builder clearRequestId() {
        
        requestId_ = getDefaultInstance().getRequestId();
        onChanged();
        return this;
      }
      /**
       * <code>string requestId = 1;</code>
       */
      public Builder setRequestIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        requestId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object functionName_ = "";
      /**
       * <code>string functionName = 2;</code>
       */
      public java.lang.String getFunctionName() {
        java.lang.Object ref = functionName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          functionName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string functionName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFunctionNameBytes() {
        java.lang.Object ref = functionName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          functionName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string functionName = 2;</code>
       */
      public Builder setFunctionName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        functionName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string functionName = 2;</code>
       */
      public Builder clearFunctionName() {
        
        functionName_ = getDefaultInstance().getFunctionName();
        onChanged();
        return this;
      }
      /**
       * <code>string functionName = 2;</code>
       */
      public Builder setFunctionNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        functionName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object jsonData_ = "";
      /**
       * <code>string jsonData = 3;</code>
       */
      public java.lang.String getJsonData() {
        java.lang.Object ref = jsonData_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          jsonData_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string jsonData = 3;</code>
       */
      public com.google.protobuf.ByteString
          getJsonDataBytes() {
        java.lang.Object ref = jsonData_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          jsonData_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string jsonData = 3;</code>
       */
      public Builder setJsonData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        jsonData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string jsonData = 3;</code>
       */
      public Builder clearJsonData() {
        
        jsonData_ = getDefaultInstance().getJsonData();
        onChanged();
        return this;
      }
      /**
       * <code>string jsonData = 3;</code>
       */
      public Builder setJsonDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        jsonData_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lmid_ = "";
      /**
       * <code>string lmid = 8;</code>
       */
      public java.lang.String getLmid() {
        java.lang.Object ref = lmid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lmid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string lmid = 8;</code>
       */
      public com.google.protobuf.ByteString
          getLmidBytes() {
        java.lang.Object ref = lmid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lmid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string lmid = 8;</code>
       */
      public Builder setLmid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lmid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string lmid = 8;</code>
       */
      public Builder clearLmid() {
        
        lmid_ = getDefaultInstance().getLmid();
        onChanged();
        return this;
      }
      /**
       * <code>string lmid = 8;</code>
       */
      public Builder setLmidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lmid_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.nguyenduc.grpc.ServiceGrpcRequest)
    }

    // @@protoc_insertion_point(class_scope:com.nguyenduc.grpc.ServiceGrpcRequest)
    private static final com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcRequest();
    }

    public static com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ServiceGrpcRequest>
        PARSER = new com.google.protobuf.AbstractParser<ServiceGrpcRequest>() {
      @java.lang.Override
      public ServiceGrpcRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServiceGrpcRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ServiceGrpcRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ServiceGrpcRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ServiceGrpcResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.nguyenduc.grpc.ServiceGrpcResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string responseCode = 1;</code>
     */
    java.lang.String getResponseCode();
    /**
     * <code>string responseCode = 1;</code>
     */
    com.google.protobuf.ByteString
        getResponseCodeBytes();

    /**
     * <code>string description = 2;</code>
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 2;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>string jsonData = 3;</code>
     */
    java.lang.String getJsonData();
    /**
     * <code>string jsonData = 3;</code>
     */
    com.google.protobuf.ByteString
        getJsonDataBytes();
  }
  /**
   * Protobuf type {@code com.nguyenduc.grpc.ServiceGrpcResponse}
   */
  public  static final class ServiceGrpcResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.nguyenduc.grpc.ServiceGrpcResponse)
      ServiceGrpcResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ServiceGrpcResponse.newBuilder() to construct.
    private ServiceGrpcResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ServiceGrpcResponse() {
      responseCode_ = "";
      description_ = "";
      jsonData_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ServiceGrpcResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              responseCode_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              description_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              jsonData_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nguyenduc.grpc.MainServiceOuterClass.internal_static_com_nguyenduc_grpc_ServiceGrpcResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nguyenduc.grpc.MainServiceOuterClass.internal_static_com_nguyenduc_grpc_ServiceGrpcResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcResponse.class, com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcResponse.Builder.class);
    }

    public static final int RESPONSECODE_FIELD_NUMBER = 1;
    private volatile java.lang.Object responseCode_;
    /**
     * <code>string responseCode = 1;</code>
     */
    public java.lang.String getResponseCode() {
      java.lang.Object ref = responseCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        responseCode_ = s;
        return s;
      }
    }
    /**
     * <code>string responseCode = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResponseCodeBytes() {
      java.lang.Object ref = responseCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responseCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 2;
    private volatile java.lang.Object description_;
    /**
     * <code>string description = 2;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int JSONDATA_FIELD_NUMBER = 3;
    private volatile java.lang.Object jsonData_;
    /**
     * <code>string jsonData = 3;</code>
     */
    public java.lang.String getJsonData() {
      java.lang.Object ref = jsonData_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jsonData_ = s;
        return s;
      }
    }
    /**
     * <code>string jsonData = 3;</code>
     */
    public com.google.protobuf.ByteString
        getJsonDataBytes() {
      java.lang.Object ref = jsonData_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jsonData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getResponseCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, responseCode_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, description_);
      }
      if (!getJsonDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, jsonData_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getResponseCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, responseCode_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, description_);
      }
      if (!getJsonDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, jsonData_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcResponse)) {
        return super.equals(obj);
      }
      com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcResponse other = (com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcResponse) obj;

      boolean result = true;
      result = result && getResponseCode()
          .equals(other.getResponseCode());
      result = result && getDescription()
          .equals(other.getDescription());
      result = result && getJsonData()
          .equals(other.getJsonData());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESPONSECODE_FIELD_NUMBER;
      hash = (53 * hash) + getResponseCode().hashCode();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (37 * hash) + JSONDATA_FIELD_NUMBER;
      hash = (53 * hash) + getJsonData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.nguyenduc.grpc.ServiceGrpcResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.nguyenduc.grpc.ServiceGrpcResponse)
        com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nguyenduc.grpc.MainServiceOuterClass.internal_static_com_nguyenduc_grpc_ServiceGrpcResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nguyenduc.grpc.MainServiceOuterClass.internal_static_com_nguyenduc_grpc_ServiceGrpcResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcResponse.class, com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcResponse.Builder.class);
      }

      // Construct using com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        responseCode_ = "";

        description_ = "";

        jsonData_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nguyenduc.grpc.MainServiceOuterClass.internal_static_com_nguyenduc_grpc_ServiceGrpcResponse_descriptor;
      }

      @java.lang.Override
      public com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcResponse getDefaultInstanceForType() {
        return com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcResponse build() {
        com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcResponse buildPartial() {
        com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcResponse result = new com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcResponse(this);
        result.responseCode_ = responseCode_;
        result.description_ = description_;
        result.jsonData_ = jsonData_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcResponse) {
          return mergeFrom((com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcResponse other) {
        if (other == com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcResponse.getDefaultInstance()) return this;
        if (!other.getResponseCode().isEmpty()) {
          responseCode_ = other.responseCode_;
          onChanged();
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          onChanged();
        }
        if (!other.getJsonData().isEmpty()) {
          jsonData_ = other.jsonData_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object responseCode_ = "";
      /**
       * <code>string responseCode = 1;</code>
       */
      public java.lang.String getResponseCode() {
        java.lang.Object ref = responseCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          responseCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string responseCode = 1;</code>
       */
      public com.google.protobuf.ByteString
          getResponseCodeBytes() {
        java.lang.Object ref = responseCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          responseCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string responseCode = 1;</code>
       */
      public Builder setResponseCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        responseCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string responseCode = 1;</code>
       */
      public Builder clearResponseCode() {
        
        responseCode_ = getDefaultInstance().getResponseCode();
        onChanged();
        return this;
      }
      /**
       * <code>string responseCode = 1;</code>
       */
      public Builder setResponseCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        responseCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string description = 2;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 2;</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 2;</code>
       */
      public Builder clearDescription() {
        
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>string description = 2;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        description_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object jsonData_ = "";
      /**
       * <code>string jsonData = 3;</code>
       */
      public java.lang.String getJsonData() {
        java.lang.Object ref = jsonData_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          jsonData_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string jsonData = 3;</code>
       */
      public com.google.protobuf.ByteString
          getJsonDataBytes() {
        java.lang.Object ref = jsonData_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          jsonData_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string jsonData = 3;</code>
       */
      public Builder setJsonData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        jsonData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string jsonData = 3;</code>
       */
      public Builder clearJsonData() {
        
        jsonData_ = getDefaultInstance().getJsonData();
        onChanged();
        return this;
      }
      /**
       * <code>string jsonData = 3;</code>
       */
      public Builder setJsonDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        jsonData_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.nguyenduc.grpc.ServiceGrpcResponse)
    }

    // @@protoc_insertion_point(class_scope:com.nguyenduc.grpc.ServiceGrpcResponse)
    private static final com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcResponse();
    }

    public static com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ServiceGrpcResponse>
        PARSER = new com.google.protobuf.AbstractParser<ServiceGrpcResponse>() {
      @java.lang.Override
      public ServiceGrpcResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServiceGrpcResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ServiceGrpcResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ServiceGrpcResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.nguyenduc.grpc.MainServiceOuterClass.ServiceGrpcResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_nguyenduc_grpc_ServiceGrpcRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_nguyenduc_grpc_ServiceGrpcRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_nguyenduc_grpc_ServiceGrpcResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_nguyenduc_grpc_ServiceGrpcResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021MainService.proto\022\022com.nguyenduc.grpc\"" +
      "]\n\022ServiceGrpcRequest\022\021\n\trequestId\030\001 \001(\t" +
      "\022\024\n\014functionName\030\002 \001(\t\022\020\n\010jsonData\030\003 \001(\t" +
      "\022\014\n\004lmid\030\010 \001(\t\"R\n\023ServiceGrpcResponse\022\024\n" +
      "\014responseCode\030\001 \001(\t\022\023\n\013description\030\002 \001(\t" +
      "\022\020\n\010jsonData\030\003 \001(\t2q\n\013MainService\022b\n\017get" +
      "UserByCardNo\022&.com.nguyenduc.grpc.Servic" +
      "eGrpcRequest\032\'.com.nguyenduc.grpc.Servic" +
      "eGrpcResponseb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_nguyenduc_grpc_ServiceGrpcRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_nguyenduc_grpc_ServiceGrpcRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_nguyenduc_grpc_ServiceGrpcRequest_descriptor,
        new java.lang.String[] { "RequestId", "FunctionName", "JsonData", "Lmid", });
    internal_static_com_nguyenduc_grpc_ServiceGrpcResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_nguyenduc_grpc_ServiceGrpcResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_nguyenduc_grpc_ServiceGrpcResponse_descriptor,
        new java.lang.String[] { "ResponseCode", "Description", "JsonData", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
