spring:
  application:
    name: orchestrator
grpc:
  server:
    port: 9090
  client:
    hello-service:
      address: 'localhost:9090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plainText
